---
#Based in hpod: https://github.com/torrlane/gitpod_haskell/blob/master/.gitpod.yml
image:
  file: Dockerfile

vscode:
  extensions:
    - hoovercj.haskell-linter@0.0.6:VpJluXvOyr9Iw7TIKg2Oyg==
    - justusadam.language-haskell@3.3.0:uqgpHstOoamig+7LyFNNVw==
    - haskell.haskell@1.1.0:Wt1BvkxTWaeCQD86YIN0fw==